# Generated by Django 4.2.4 on 2024-06-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainees',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='trainees',
            name='goal',
            field=models.CharField(choices=[('CUTTING', 'Cutting'), ('BULKING', 'Bulking'), ('WEIGHTLOSS', 'Weightloss'), ('PYSIQUE', 'Physique')], default='WEIGHTLOSS', max_length=20),
        ),
        migrations.AddField(
            model_name='trainees',
            name='health_issues',
            field=models.CharField(choices=[('DIABETES', 'Diabetes'), ('CHOLESTEROL', 'Cholesterol'), ('THYROID', 'Thyroid'), ('OTHERS', 'Others'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainees',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
